### ISSUE TITLE
Error while run cli command indexer:reindex - Magento 2.4.3

### ISSUE THREAD

**Issue by motau** [zepgram/module-disable-search-engine#10]
When we run the Magento2 (`v2.4.3`) indexer via CLI, an exception occurs at the `Catalog Search index`, which is apparently not yet caught by the Disable-Search-Engine-Module (`v0.1.1`). This error occurs in all our environments.

```
Catalog Search index [2022-05-04 07:39:58] main.CRITICAL: Type Error occurred when creating object: Magento\Search\Model\EngineResolver, Argument 2 passed to Magento\Search\Model\EngineResolver::__construct() must be of the type array, null given, called in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121 [] []
process error during indexation process:
Type Error occurred when creating object: Magento\Search\Model\EngineResolver, Argument 2 passed to Magento\Search\Model\EngineResolver::__construct() must be of the type array, null given, called in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121
```

**Comment by zepgram** [comment]
Could you tell me how your indexer are configured (save by schedule/on save) ?
I'll try to reproduce

**Comment by motau** [comment]
The indexer mode makes no difference.

Just now I found another problem with the same message as the origin: The content of the store adminhtml catalog config page `{shopBaseUrl}/admin/system_config/edit/section/catalog/` remains white . On the server the same exception appears on this route as on the CLI run.

**Comment by zepgram** [comment]
> The indexer mode makes no difference

I need a snapshot of your indexer configuration to be on the same condition as you.

Did you reproduce this error with a fresh magento 2.4.3 installation ?

**Comment by motau** [comment]
1. what do you mean with "snapshot"? Do you need the configuration output?
2. We made an upgrade of an existing shop (because of productive database) - the option of a fresh installation is not suitable for us. The build process runs through a complete gitlab pipeline where no error occurs (using the same database but without any productive data and without running any index)

**Comment by zepgram** [comment]
1. I wanted a screenshot
2. This module have been tested and works on fresh installtion from version 2.3.0 to 2.4.4

If take a look on your error, it's related  to the class "EngineResolver", this class contains an array in his constructor, which is injected with di.xml here:
https://github.com/zepgram/module-disable-search-engine/blob/main/etc/di.xml#L19

Your error could occure for 2 reasons:
1. cache config has not been flushed correctly
2. this module has not been activated (check the config.php file)

**Comment by motau** [comment]
Unfortunately, both points are not the reason, Complete Cache is fresh, your module is enabled in config and shown in cli mod:status

And yes, I completely understand your implemention, it is really cool, but ...
Could it be the DI is not really working while cli process or in adminhtml ? Maybe it is an App Area problem?

**Comment by zepgram** [comment]
Can you confirm that you have this configuration in your store settings ?
![image](https://user-images.githubusercontent.com/16258478/166666418-62f805d3-10da-4a6d-bcbd-566e09b5f98b.png)

**Comment by motau** [comment]
No, I cannot check because of the error at the blank adminhtml catalog config page ;-) 

I just tested to set the value directly to an ENV (`CONFIG__DEFAULT__CATALOG__SEARCH__ENGINE: "none"`) and after no change I stored it directly as new database entry in `core_config_data` (`'default',0,'catalog/search/engine','none'`) ... BUT unfortunately, nothing helps ... any ideas?

**Comment by motau** [comment]
SOLVED: Hey, finally I have solved our problem: at build time the module was not explicitly part of the config.php / modules. Such additional modules without config entry are active by default in magento, and yes, even cli mod:status sayed: activated. BUT: while generating the build we MUST have activate such modules in config.php to get properly generated code. So ... my mistake. Sorry for taking your time
