### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by ac0049** [zepgram/module-disable-search-engine#11]
Hello,

I installed the module '0.1.0' on Magento 2.4.3 p-1
Getting an error when compiling setup:di:compile
`Impossible to process constructor argument Parameter #0 [ <required> Magento\Elasticsearch\Mode
  l\ResourceModel\Fulltext\Collection\SearchResultApplierFactory $elasticSearchResultApplierFacto
  ry ] of Amasty\Shopby\Model\ResourceModel\Fulltext\Collection\SearchResultApplier class`

` Class Magento\Elasticsearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplierFactory
  does not exist`

We have Amasty_LayeredNavigation installed on the site.

**Comment by zepgram** [comment]
Hello,

You must take a look deeper in this module and validate that it doesn't require fulltext indexation from search engine to work correctly.
It looks like it does, so you cannot disable elasticsearch.

**Comment by ac0049** [comment]
Thank you!
