### ISSUE TITLE
Magento 2.4.5 doesn't works

### ISSUE THREAD

**Issue by brenik** [zepgram/module-disable-search-engine#14]
fox@fox:/var/www/sert.loc$ composer require zepgram/module-disable-search-engine --ignore-platform-reqs -v
> pre-command-run: Laminas\DependencyPlugin\DependencyRewriterPluginDelegator->onPreCommandRun
> pre-command-run: Magento\ComposerRootUpdatePlugin\Plugin\PluginDefinition->checkForDeprecatedRequire
Found package xox/theme-frontend (0.0.1) in file theme-frontend.zip
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^0.3.0 for zepgram/module-disable-search-engine
./composer.json has been updated
Running composer update zepgram/module-disable-search-engine
> command: MagentoHackathon\Composer\Magento\Plugin_composer_tmp3->onCommandEvent
> pre-update-cmd: Magento\InventoryComposerInstaller\Plugin_composer_tmp4->initModuleDeployment
Loading composer repositories with package information
Found package xox/theme-frontend (0.0.1) in file theme-frontend.zip
> pre-pool-create: Laminas\DependencyPlugin\DependencyRewriterPluginDelegator_composer_tmp0->onPrePoolCreate
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
> pre-pool-create: Magento\ComposerDependencyVersionAuditPlugin\Plugin_composer_tmp2->prePoolCreate
Updating dependencies
Dependency resolution completed in 0.028 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires zepgram/module-disable-search-engine ^0.3.0 -> satisfiable by zepgram/module-disable-search-engine[0.3.0].
    - zepgram/module-disable-search-engine 0.3.0 requires magento/framework ^103.0.6 -> found magento/framework[103.0.6, 103.0.6-p1, 103.0.6-p2] but the package is fixed to 103.0.5 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require zepgram/module-disable-search-engine:*" to figure out if any version is installable, or "composer require zepgram/module-disable-search-engine:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by zepgram** [comment]
You must require the version 2.1

**Comment by brenik** [comment]
Thanks.
composer require zepgram/module-disable-search-engine:0.2.1  helps my!
