### ISSUE TITLE
Getting `We can't find products matching the selection.` on Magento 2.4.6

### ISSUE THREAD

**Issue by atty31** [zepgram/module-disable-search-engine#17]
Hi,
I followed the instructions , but I m getting the We can't find products matching the selection message on the category page, beside that I have products .
On the setup:upgrade command I don't get the ES error.
Any thoughts about why I don't see products on the category page?
Thanks

**Comment by zepgram** [comment]
Category pages information are displayed from ES. 
This module is designed to completely disable native ES (for headless integration for example), so you cannot use the native category page feature.

If you want to fallback on MySQL legacy system, you should use this module instead: https://github.com/swissup/module-search-mysql-legacy

**Comment by atty31** [comment]
Hi @zepgram,
Thanks for the recommandation
