### ISSUE TITLE
ElasticSearch 8 support?

### ISSUE THREAD

**Issue by bfontaine** [zepgram/module-disable-search-engine#19]
Hello,
Does this module support ElasticSearch 8? The README says it removes `magento/module-elasticsearch-6` and `magento/module-elasticsearch-7` but not `magento/module-elasticsearch-8`. Would that be hard to support?
Thanks.

**Comment by zepgram** [comment]
Hello,

The module completely remove Elasticsearch engine on all version. There is
an extra part optimization where module are totally removed from composer,
in composer.json, but the module should still work even if module is in
Magento base code.

**Comment by bfontaine** [comment]
Ok, thank you!
