### ISSUE TITLE
how to do this with a new install

### ISSUE THREAD

**Issue by f1-outsourcing** [zepgram/module-disable-search-engine#2]
If I have a fresh install, how should I do this? Because these are not working then

```
 php -d disable_functions=none bin/magento module:uninstall Magento_AdvancedSearch
You cannot run this command because the Magento application is not installed.

```

`php -d disable_functions=none ../composer-2.phar remove magento/AdvancedSearch`

**Comment by zepgram** [comment]
Hello, you just have to add the module in your composer.json in the dependency part.
(You can do this by running the command line `composer require zepgram/module-disable-search-engine`)

If you added it manually in composer.json without the composer require, then you just have to run composer update.

The module that you are trying to uninstall is uninstalled by the module himself via composer.

**Comment by f1-outsourcing** [comment]
using this command failed

```
bash-4.2$ php -d disable_functions=none ../composer-2.phar require zepgram/module-disable-search-engine
Using version ^0.0.2 for zepgram/module-disable-search-engine
./composer.json has been updated
Running composer update zepgram/module-disable-search-engine
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - magento/magento2ce is present at version 2.4.2 and cannot be modified by Composer
    - zepgram/module-disable-search-engine[0.0.2] cannot be installed as that would require removing magento/magento2ce[2.4.2]. They both replace magento/module-advanced-search and thus cannot coexist.
    - Root composer.json requires zepgram/module-disable-search-engine ^0.0.2 -> satisfiable by zepgram/module-disable-search-engine[0.0.2].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

```

If I change this composer.json directly with something like this (I do not have the module magento/module-elasticsearch-catalog-permissions)

```
sed -i '/"require": {/a \ \ \ \ \ \ \ \ "zepgram/module-disable-search-engine": "*",' composer.json
sed -i '/magento\/module-advanced-search/d' composer.json
sed -i '/magento\/module-elasticsearch/d' composer.json
sed -i '/magento\/module-elasticsearch-6/d' composer.json
sed -i '/magento\/module-elasticsearch-7/d' composer.json

sed -i '/magento\/module-catalog-search/d' composer.json
sed -i '/elasticsearch\/elasticsearch/d' composer.json
sed -i '/magento\/module-search/d' composer.json
```

I still keep getting this error when installing

Could not validate a connection to Elasticsearch. No alive nodes found in your cluster

Are you sure this should work in a fresh install?

**Comment by zepgram** [comment]
Yes, this should work by adding only the `zepgram/module-disable-search-engine: '*'`. You just have to add the module in the "requires" node.

**Comment by f1-outsourcing** [comment]
FWIW I switched back to magento-lts, I am actually quite pleased with this project, this 1.9 continuation is much faster, uses much less resources and better in secured in shared hosting. (compared to this 2.x)

Did you know that elastic changed it's license and is not opensource anymore? I have been asking adobe what they are going to do about this. Because it is weird that their opensource project has a forced dependency on closed source. But I only seem to get replies from annoyed developers.

**Comment by zepgram** [comment]
Well that's why I made this module, to remove ES dependency from Magento 2.
The first reason why they switched from mysql engine to ES engine is for performance and "best-practice" (if you want my opinion they should rework the front-end framework and remove knockoutJS instead of doing this kind of things).

In my case I made this module because my client doesn't use the Magento front-end, Magento is only consumed with graphQL API, which provide great performance, also front-end is not based on Magento so, you can make a PWA or whatever you want.

**Comment by f1-outsourcing** [comment]
> 
> 
> Well that's why I made this module, to remove ES dependency from Magento 2.
> The first reason why they switched from mysql engine to ES engine is for performance and "best-practice" (if you want my opinion they should rework the front-end framework and remove knockoutJS instead of doing this kind of things).

I think, I get a bit what you are saying (no knowing to much about magento frontend). It is just weird how these days rookies seem to manage such projects. I honestly think it is weird that you have to do this with your module, and magento is not offering this functionality out-of-the-box. That is the whole idea about having a module structure  not? So you can remove/disable them.

> In my case I made this module because my client doesn't use the Magento front-end, Magento is only consumed with graphQL API, which provide great performance, also front-end is not based on Magento so, you can make a PWA or whatever you want.

Interesting, currently I need to get something up and running quickly. In my case clients already decided to do a purchage, and I am redirecting them to magento as administrative environment. I want the order payments processed automatically.
