### ISSUE TITLE
Not working for Magento ver. 2.4.6 and Magento ver. 2.4.7-p2 (Openseach)

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [zepgram/module-disable-search-engine#20]
We have installed this module in 2.4.6 and 2.4.7-p2 it disables the module and indexing is done properly with all commands but it breaks GraphQl queries.
GraphQl queries like products etc are not working and give an empty response with no error.

`{products(filter:{sku:{eq:"roundstickers"}}){items{id name sku media_gallery { url label position disabled }}}}`

**Comment by zepgram** [comment]
Hello, you cannot query native graphQL products since it relies on the
Elasticsearch engine. You need your own elasticsearch query or external
providers like Nosto, Algolia, PIM engine etc... to display your products
in frontend.
