### ISSUE TITLE
I can't get this to install - what am I doing wrong?

### ISSUE THREAD

**Issue by julianne49** [zepgram/module-disable-search-engine#4]
Hello, please be patient with me. I am new to Magento 2 & just trying to figure this out. 

When I ran the command: composer require zepgram/module-disable-search-engine
bin/magento module:enable Zepgram_DisableSearchEngine
bin/magento setup:upgrade in composer - I got the following error:

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
]# bin/magento module:enable Zepgram_DisableSearchEngine
-bash: bin/magento: Permission denied
]# bin/magento setup:upgrade
-bash: bin/magento: Permission denied
]#
File permissons are set to 0644, Directories: 0755. (even tried setting files to: 660 & folders to: 770) Same message.
 (I deleted my site info from the above)

Any help would be greatly appreciated. Also - once this is working, will I be able to add an extension for search or will this disable the function forever? Thank you.

**Comment by zepgram** [comment]
Hello, it looks like you got an issue with permissions, you can apply correct rights by running this:
```
sudo find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \; \\
&& sudo find var vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} \; \\
&& sudo find ./var ./generated -type d -exec chmod 777 {} \; \\
&& sudo chmod u+x bin/magento \\
```

If you install this module, the whole native feature for search engine will be disabled.
But as an example, if you use an other engine (like Algolia) it's fine, because Algolia doesn't use the native magento search engine.

**Comment by julianne49** [comment]
Hello - thanks for responding. I am just getting back to this & will try it later today.

 

Once again - thank you.

 

Camille Smith
