### ISSUE TITLE
Magento_InventoryElasticsearch

### ISSUE THREAD

**Issue by sprankhub** [zepgram/module-disable-search-engine#5]
Thanks for this module!

I just installed it and noticed that the module `Magento_InventoryElasticsearch` is still present and enabled, even though I expected it to be replaced as well. I did not run into issues with it yet, but maybe it is worth having a look at that?

**Comment by zepgram** [comment]
Yup! I missed that, thanks for watching. I'll made a new release to disable it.

**Comment by sprankhub** [comment]
Cool, thanks!
