### ISSUE TITLE
In Category Product Not Showing

### ISSUE THREAD

**Issue by niku0911** [zepgram/module-disable-search-engine#6]
Added Module with Composer but facing issue in Category page Product not display can you help on this, in log we faced this type of error
![image](https://user-images.githubusercontent.com/50168477/134533610-02177e55-ac23-4510-9da9-26e64a23495f.png)

**Comment by zepgram** [comment]
Hello, 

That's the purpose of this module. You cannot install it if you need to display product (this will return no result for Graphql for example)

I can give it a try but I'm not sure this will work.

**Comment by zepgram** [comment]
I give it a try on community edition version 2.4.3 and I don't have fatal error:
![image](https://user-images.githubusercontent.com/16258478/134770953-c5de9a9d-754a-4af1-80a6-9dae13fd0216.png)

Could you give me your product edition (community/enterprise) and your current magento version ? 

Thanks
