### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Eddcapone** [zepgram/module-disable-search-engine#9]
I installed the extension on a fresh magento. Then I tried to uninstall the extension again with `composer remove zepgram/module-disable-search-engine`.

But now I get this error if I execute `php bin/magento setup:upgrade`

**Missing required argument $engines of Magento\Search\Model\EngineResolver**

**Comment by Eddcapone** [comment]
I had to execute `composer install` with composer 2 now it works again.

**Comment by zepgram** [comment]
Cleaning generated files (rm -rf generated) and cleaning cache should be enough to disable this module
